version: '3.3'
services:
  agent:
    image: skywalking-app/project:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 8888:8080
    environment:
      SW_AGENT_NAME: agent
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: 192.168.112.98:31180
      collector.ribbon.listOfServers: 100.100.100.121:11800
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - webnet
networks:
  webnet:
