
version: '3.3'
services:
  oap:
    image: apache/skywalking-oap-server:6.0.0-GA-timezone
    container_name: oap
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      JAVA_OPTS: " -Xms512M -Xmx1024M"
    volumes:
      - ./config:/skywalking/config:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ui:
    image: apache/skywalking-ui:6.0.0-GA-timezone
    container_name: ui
    restart: always
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: " -Xms512M -Xmx1024M"
      collector.ribbon.listOfServers: oap:12800
      collector.ribbon.ReadTimeout: 20000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
